### PR TITLE
ec_deployment: Add support for deployment aliases

### LINKED ISSUE #287: ec_deployment: support deployment aliases
## Overview
Need to support the new deployment alias feature.

## Possible Implementation
have a new property for the deployment:
```alias = "my-alias"```

/cc @shubhaat

### PR DESCRIPTION
**Pull request by marclop**
## Description

Adds support for deployment aliases on both the `ec_deployment` resource
and `ec_deployment` datasource.

## Related Issues

Closes #287 

## How Has This Been Tested?

Manual, unit and acceptance tested.

## Types of Changes

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by alaudazzi — APPROVED** [review]
LGTM for the .md files

**Review by karencfv — APPROVED** [review]
🏅

**Comment by marclop** [comment]
`TestAccDeployment_basic_config` seems to return with a non-empty plan on step 2/3:

```
12:11:27  === CONT  TestAccDeployment_basic_config
12:11:27      deployment_basic_test.go:95: Step 2/3 error: After applying this test step, the plan was not empty.
12:11:27          stdout:
12:11:27          
12:11:27          
12:11:27          Terraform used the selected providers to generate the following execution
12:11:27          plan. Resource actions are indicated with the following symbols:
12:11:27            ~ update in-place
12:11:27          
12:11:27          Terraform will perform the following actions:
12:11:27          
12:11:27            # ec_deployment.basic will be updated in-place
12:11:27            ~ resource "ec_deployment" "basic" {
12:11:27                ~ alias                  = "terraform-acc-tnvcsx8mmv" -> "basic"
12:11:27                  id                     = "36f2ce73ef9c96b8f5c943a451098043"
12:11:27                  name                   = "terraform_acc_tnvcsx8mmv"
12:11:27                  tags                   = {}
12:11:27                  # (6 unchanged attributes hidden)
12:11:27          
12:11:27          
12:11:27          
12:11:27          
12:11:27                  # (4 unchanged blocks hidden)
12:11:27              }
12:11:27          
12:11:27          Plan: 0 to add, 1 to change, 0 to destroy.
```

I'll take a look.

**Comment by marclop** [comment]
Tests look alright, I think we can merge this. @karencfv

**Pull request merged**
