### PR TITLE
deps: update sdk version to include MS46 changes

### PR DESCRIPTION
**Pull request by karencfv**
## Description
Update sdk version to include MS46 changes

## Motivation and Context
Necessary for https://github.com/elastic/terraform-provider-ec/issues/60

## How Has This Been Tested?
Unit 

## Types of Changes

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by marclop** [comment]
But `MS-46` is not yet in production :)

**Comment by karencfv** [comment]
Wanted to get started on https://github.com/elastic/terraform-provider-ec/issues/60, but OK I'll wait 😄

**Comment by marclop** [comment]
I mean, we can merge it so you can get started, but it's going to be difficult to test the way we have things set up

**Comment by marclop** [comment]
That said, it's testable in `ce-aws`

**Comment by karencfv** [comment]
>  but it's going to be difficult to test the way we have things set up

True, also I wouldn't be able to add acceptance tests. It's OK I can wait :)

**Pull request closed without merging**
