### PR TITLE
Fixed error when universal profiling is activated

### PR DESCRIPTION
**Pull request by 3kt**
The `profiling` and `symbols` endpoints were not being read from the response payload, ~causing an error~.

## Description
When activating universal profiling in Kibana (`/app/profiling` in Kibana), several new endpoints are added to the deployment:

image

These were not recognized by the provider, ~leading to a deadlock situation where the deployment cannot be administered through terraform anymore. This PR fixes this problem~. This PR adds the ability to correctly parse the endpoints in the response.

## Related Issues
~Fixes https://github.com/elastic/terraform-provider-ec/issues/781~
The related issue is fixed in 0.6+.

## Motivation and Context
See the above description.

## How Has This Been Tested?
Unit tested.
AFAICT there's no acceptance test covering this, it might make sense to write one though?
I've also ran the setup described in the issue linked above, and was able to complete the workflow without error.

## Types of Changes
- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improves code quality but has no user-facing effect)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Readiness Checklist
- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [ ] All new and existing tests passed

Regarding the acceptance tests, I tried to run them per the contributing guidelines, but faced quite some failures with cryptic error messages. A second pass will be very welcome, as I'm not sure I ran them properly.

_edit: modified PR definition to reflect that this is a new feature rather than a bug fix_

### CODE REVIEW

**Comment by tobio** [comment]
@3kt are you able to add a file to the [changelog](https://github.com/elastic/terraform-provider-ec/blob/master/.changelog/) for this. You can probably use [this](https://github.com/elastic/terraform-provider-ec/blob/master/.changelog/777.txt) one as an example.

**Comment by tobio** [comment]
> The profiling and symbols endpoints were not being read from the response payload, causing an error.

Firstly, this PR is awesome, and it's great to include these endpoints in the resource. That said, this PR does not fix the linked issue, that issue is not present in 0.6 and higher.

**Comment by 3kt** [comment]
> @3kt are you able to add a file to the [changelog](https://github.com/elastic/terraform-provider-ec/blob/master/.changelog/) for this. You can probably use [this](https://github.com/elastic/terraform-provider-ec/blob/master/.changelog/777.txt) one as an example.

I added the corresponding `783.txt` file @tobio  :)
Is there anything else I should edit?

**Review by tobio — APPROVED** [review]
LGTM

**Pull request merged**
