### PR TITLE
build: fix build to work on darwin/arm64

### LINKED ISSUE #314: darwin/arm64 build
## Overview

Please provide a build for the new ARM based Macs (M1).

Currently, the following error is shown when using this provider:

```
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/elastic/ec v0.1.1 does not have a package available for your current platform,
│ darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms.
│ Other versions of this provider may have different platforms supported.
╵
````
## Possible Implementation

Add the platform to the Go build and provide binaries.

## Your Environment

```
❯ terraform version
Terraform v0.15.3
on darwin_arm64
```

### PR DESCRIPTION
**Pull request by derkoe**
## Description
- Update golangcilint to current version
- Replace gobin with `go install``
- Replace hardcoded arch in Makefile.build with `uname -m`

## Related Issues
Closes #314

## Motivation and Context

This makes the build work on ARM Macs

## How Has This Been Tested?

I have run `make install` and used the module in 

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improves code quality but has no user-facing effect)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Readiness Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Review by marclop — COMMENTED** [review]
Thank you for opening this PR @derkoe, they're all good additions and we seem to have missed the arm64 build.

I've got a couple of comments on your PR and you also forgot to remove the references to `gobin` in the `build/Makefile.tools` file.

`make lint unit validate-examples install` should always pass.

**Comment by derkoe** [comment]
@marclop thx for your review - added your suggestions

**Comment by marclop** [comment]
It seems that you only addressed my suggestions on the review but didn't fix my other comment: 

> 've got a couple of comments on your PR and you also forgot to remove the references to gobin in the build/Makefile.tools file.

**Review by marclop — APPROVED** [review]
LGTM

**Comment by marclop** [comment]
Jenkins test this please

**Pull request merged**
