### PR TITLE
Prepare release 0.12.2

### PR DESCRIPTION
**Pull request by dimuon**
Prepare release 0.12.2.

It's needed to release https://github.com/elastic/terraform-provider-ec/pull/866.

### CODE REVIEW

**Comment by dimuon** [comment]
The tests fail due to some changes to API.

**Review by gigerdo — APPROVED** [review]

**Comment by GeorgeGkinis** [comment]
Hello @gigerdo 

Do you have an estimation about when v0.12.2 will be released?
We really could use PR #866.

Thanks!

**Comment by dimuon** [comment]
@GeorgeGkinis , sorry for the delay - we faced with a number of failed acceptance tests which was caused by old DTs/ICs deprecation in API and also discovered another defect along the way. Addressing these findings took some time.
TL/DR, we will proceed with the release.

**Comment by GeorgeGkinis** [comment]
Thanks for the feedback!

I figured it out that the interface changes could prove to be time consuming. 

Good to hear they are resolved!

Cheers.

**Comment by dimuon** [comment]
There are 3 flaky acceptance tests which failed:
- `TestAccDatasource_trafficfilter` failed  with `Failed to read deployment traffic filter ruleset after create`;
- `TestAccDeployment_basic_defaults_first` and `TestAccDeployment_integrationsServer` failed because plan which adds IntegrationsServer was completed before IntergrationServer's endpoints became available (we have a ticket for this).

**Comment by dimuon** [comment]
https://github.com/elastic/terraform-provider-ec/releases/tag/v0.12.2

**Pull request merged**
