### PR TITLE
ec_extension: Use SDK APIs and small refactor

### PR DESCRIPTION
**Pull request by karencfv**
## Description
Updates the cloud-sdk-go dependency to the latest commit (1547ae0)
to include the [new extension APIs](https://github.com/elastic/cloud-sdk-go/pull/269).

Additionally, The `ec_extension` resource has been updated to use
these new APIs and I have made a slight refactor to improve  readability.

## Related Issues
Closes: https://github.com/elastic/terraform-provider-ec/issues/102

## How Has This Been Tested?
Acceptance tests

## Types of Changes

- [x] Refactoring (improves code quality but has no user-facing effect)

## Readiness Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by karencfv** [comment]
@marclop I just realised this resource was named `ec_extension` instead of `ec_deployment_extension`. I think we should opt for the latter following the pattern we have for `ec_deployment_traffic_filter`, as this functionality is part of the deployments API. What do you think? If you agree I'll make that change as part of this PR

**Review by marclop — APPROVED** [review]
Looks good.

**Comment by marclop** [comment]
@karencfv I'm fine with changing the resource name to have a `deployment_` prefix. The API isn't part of the deployments API but the extensions aren't really usable outside of deployments themselves, feel free to change it in this PR.

**Comment by karencfv** [comment]
Cool, I'll change it then :) It is part of the deployments API though https://www.elastic.co/guide/en/cloud/current/Deployments_-_Extensions.html#ec_request_46

**Review by marclop — APPROVED** [review]
Looks good

**Pull request merged**
