### PR TITLE
ec_deployment:  Add importer

### PR DESCRIPTION
**Pull request by ggsood**
Terraform EC Deployment Import code

### Tests

make test 

after running Terraform command

`terraform import ec_deployment.example_deploy 3sdasdwqdw3q222222ed`

### CODE REVIEW

**Comment by marclop** [comment]
@ggsood Thanks for your contribution, but I think the change should also include the acceptance tests which add / validate the imported resource under the `ec/acc` folder, before merging this change.
This might incur changes in your Elastic Cloud or ECE installation, and that's why we were going to try and tackle this internally, but let me know if you would like to do it yourself.

Additionally, I think it's a good idea to let us know if you're planning to take an issue by commenting on the issue. This is a little bit better for coordination and we can also let you know any possible complexities or problems you might run when trying to address it, if we have them in mind in case issues are vague or placeholders which some of them are.

**Comment by ggsood** [comment]
thanks @marclop will update the issue and will write some acceptance tests, might require your help with the Elastic Cloud installation, as i am using the trial version to test out the code.

**Comment by marclop** [comment]
That sounds good, I will assign the issue to you, you can limit the amount of resources which will be created by just running a single test with the `TEST_NAME=<acceptance test name`:

```sh
$ make testacc TEST_NAME=TestAccDeployment_basic
-> Formatting Go files...
-> Formatting Terraform documentation blocks...
-> Done.
-> Running terraform acceptance tests...
=== RUN   TestAccDeployment_basic
=== PAUSE TestAccDeployment_basic
=== CONT  TestAccDeployment_basic
--- PASS: TestAccDeployment_basic (628.88s)
PASS
ok  	github.com/terraform-providers/terraform-provider-ec/ec/acc	629.197s
```

Additionally, the README file contains some instructions on generating API Keys and exporting the acceptance tests.

**Comment by RohitK89** [comment]
Bumping as a hopeful consumer of this very useful PR :)

**Comment by marclop** [comment]
@ggsood I can take over this PR and make sure the import works as expected if you don't mind.

**Comment by ggsood** [comment]
Apologies @marclop got busy with some personal issue. Yes please feel free to make any changes.

**Comment by marclop** [comment]
I'm closing this PR and starting work on a new one

**Pull request closed without merging**
