### PR TITLE
Plugin framework 1.2

### PR DESCRIPTION
**Pull request by tobio**
## Description
Upgrades the plugin framework version

## Related Issues
Fixes https://github.com/elastic/terraform-provider-ec/issues/607

## How Has This Been Tested?

Unit tests, acceptance tests

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improves code quality but has no user-facing effect)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Readiness Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by dimuon** [comment]
@tobio , thanks a lot for the PR.
Does it make sense to drop CLI 1.3.9 requirement in scope of this PR?

**Comment by tobio** [comment]
I was still seeing the same issue running 1.4 in testing IIRC. I'll take another look.

**Review by dimuon — APPROVED** [review]
👍 Thanks a lot for the PR

**Comment by dimuon** [comment]
@tobio , so we cannot yet drop 1.3.9 requirement, right? 
It looks like the PR misses changelog :)

**Pull request merged**
