### PR TITLE
Remove validators.Known() on endpoint.

### PR DESCRIPTION
**Pull request by GeorgeGkinis**
This removes validators.Known() from the ec.endpoint parameter.
This will allow setting ec.endpoint as a variable and prevents an error "Value must be known" during terraform plan

## Description

We want to dynamically change the endpoint URL using variables during CI/CD deployments.
It is currently not possible because during terraform plan **ec.endpoint** is not filled with the given variable:

```
provider "ec" {
  endpoint = var.ECE_CONSOLE_URL
  apikey = var.ECE_CONSOLE_API_KEY
}
```
local.auto.tfvars:
```
ECE_CONSOLE_URL = "https://console.ece.mydomain.com"
ECE_CONSOLE_API_KEY = "myapikey"
```

The endpoint field is also declared as [optional ](https://github.com/elastic/terraform-provider-ec/blob/6f6c1b81b05316c7959039f6320e67dd10de173e/ec/provider.go#L134) in the code and according to [documentation ](https://registry.terraform.io/providers/elastic/ec/latest/docs#endpoint) has a default value of "https://api.elastic-cloud.com"

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improves code quality but has no user-facing effect)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Readiness Checklist

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by GeorgeGkinis** [comment]
@tobio Could you please take a look at this?
I am curious why validators.Known() was needed for ec.endpoint and as such if this is a breaking change.

I suppose not, because everyone had to explicitly set ec.endpoint up until now.

Thanks!

**Comment by gigerdo** [comment]
Yes, I think you are right. It should be fine to remove it to allow using variables in the config.

cc @dimuon

**Comment by GeorgeGkinis** [comment]
@gigerdo I believe the [regression test error](https://github.com/elastic/terraform-provider-ec/pull/866/checks#step:9:71) is unrelated to my change?

**Comment by dimuon** [comment]
@GeorgeGkinis , looks like it caused by https://github.com/hashicorp/terraform-provider-aws/issues/39676.

**Review by dimuon — APPROVED** [review]

**Comment by GeorgeGkinis** [comment]
@dimuon Should I make another pull request to implement the [workaround ](https://github.com/hashicorp/terraform-provider-aws/issues/39676#issuecomment-2406560448)in [providers.tf](https://github.com/elastic/terraform-provider-ec/blob/6f6c1b81b05316c7959039f6320e67dd10de173e/examples/deployment_ec2_instance/provider.tf#L11) or should we wait until it is resolved by Hashicorp?

**Comment by dimuon** [comment]
@GeorgeGkinis let's proceed with the workaround. Thanks for the contribution!

**Comment by GeorgeGkinis** [comment]
@dimuon Check https://github.com/elastic/terraform-provider-ec/pull/867

**Comment by GeorgeGkinis** [comment]
@dimuon Maybe try running these test once again?
I rebased this branch on top of master with https://github.com/elastic/terraform-provider-ec/pull/867

**Comment by GeorgeGkinis** [comment]
@dimuon Njoy the weekend!

**Comment by dimuon** [comment]
Thank you @GeorgeGkinis, wishing you a great weekend too!

**Comment by GeorgeGkinis** [comment]
@dimuon Is there a known release date with this fix?
We cannot deploy from our CI/CD until this is released, but we can wait a week or 2.

**Comment by dimuon** [comment]
@GeorgeGkinis , there is no specific date for the new release but I suppose we can release the fix soon.

**Pull request merged**
