### PR TITLE
dependencies: Update terraform-plugin-sdk to v2.0.4

### PR DESCRIPTION
**Pull request by karencfv**
## Description
Updates the terraform-plugin-sdk dependency to v2.0.4

### CODE REVIEW

**Review by marclop — APPROVED** [review]
Looks good, but it worries me that the id changes when it's protected by that if clause https://github.com/elastic/terraform-provider-ec/blob/master/ec/ecdatasource/deploymentsdatasource/datasource.go#L62

**Comment by karencfv** [comment]
@marclop I honestly don't remember why I put the `if` clause there. I can remove it, but I'll do it in a follow up PR as I feel like it falls out of the scope of this one

**Comment by marclop** [comment]
oh, I think that the clause should be there, no need to re-generate the ID every single read?

**Comment by karencfv** [comment]
Ah! right, got it. I misread what you had written. I hadn't noticed that until you mentioned it

Hmmmmm 🤔

**Comment by karencfv** [comment]
Ah! I know why the ID changes. It's because the test has two checks. it tests `data.ec_deployment` which sets the ID to `d.SetId(deploymentID)` first, and `data.ec_deployments` which sets ID to `d.SetId(resource.UniqueId())` afterwards.

**Pull request merged**
